export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const LOAD_MENU_LIST = 'LOAD_MENU_LIST';
export const ADD_MENU_ITEM = 'ADD_MENU_ITEM';
export const UPDATE_MENU_ITEM = 'UPDATE_MENU_ITEM';
export const DELETE_MENU_ITEM = 'DELETE_MENU_ITEM';
export const UPDATE_MENU_SOLDOUT = 'UPDATE_MENU_SOLDOUT';
