export const BUTTON = 'BUTTON';

export const BASE_URL = 'http://localhost:3000';

// HTTP methods
export const POST = 'POST';
export const DELETE = 'DELETE';
export const PUT = 'PUT';

// actions
export const LOAD_MENUITEMS_SUCCESS = 'LOAD_MENUITEMS_SUCCESS';
export const LOAD_MENUITEMS_FAIL = 'LOAD_MENUITEMS_FAIL';
export const ADD_MENUITEM_SUCCESS = 'ADD_MENUITEM_SUCCESS';
export const ADD_MENUITEM_FAIL = 'ADD_MENUITEM_FAIL';
export const DELETE_MENUITEM_SUCCESS = 'DELETE_MENUITEM_SUCCESS';
export const DELETE_MENUITEM_FAIL = 'DELETE_MENUITEM_FAIL';
export const EDIT_MENUITEM_SUCCESS = 'EDIT_MENUITEM_SUCCESS';
export const EDIT_MENUITEM_FAIL = 'EDIT_MENUITEM_FAIL';
export const SOLDOUT_MENUITEM_SUCCESS = 'SOLDOUT_MENUITEM_SUCCESS';
export const SOLDOUT_MENUITEM_FAIL = 'SOLDOUT_MENUITEM_FAIL';
