export const BUTTON = 'BUTTON';

// actions
export const LOAD_MENUITEMS = 'LOAD_MENUITEMS';
export const SAVE_MENUITEMS = 'SAVE_MENUITEMS';
export const ADD_MENUITEM = 'ADD_MENUITEM';
export const DELETE_MENUITEM = 'DELETE_MENUITEM';
export const EDIT_MENUITEM = 'EDIT_MENUITEM';
export const SOLDOUT_MENUITEM = 'SOLDOUT_MENUITEM';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
